# config/meta.yml

meta_title: "L'Agenceur Lyonnais - Ameublement d'intérieur pour investisseurs professionnels et particuliers à Lyon"
meta_description: "L'Agenceur Lyonnais est spécialiste dans l'ameublement de votre appartement ou maison à Lyon et sa région. Nous nous chargeons de tout : de la sélection au montage final chez vous..."
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
